### ISSUE TITLE
No such file or directory: 'VERSION'

### ISSUE THREAD

**Issue by smujiang** [Peter554/StainTools#17]
I got an error when I tried to install staintools with pip.
```
$ pip install staintools
Collecting staintools
  Using cached https://files.pythonhosted.org/packages/3d/64/7856a7009d49ab4661abb2618c4deccf8f7330634585408c81db93f55fb2/staintools-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-up7ulmum/staintools/setup.py", line 6, in <module>
        with open('VERSION') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-up7ulmum/staintools/
```
There is no VERSION in this tar. Hope you can fix it.

**Comment by Peter554** [comment]
Sorry, that bug should be fixed now.
